import Head from "next/head";
import { NavigationItems } from "../../configs/navigation";
import { FooterComponent } from "../footer";

import { Navigation } from "../navigation";

interface IMasterLayoutComponent {
  children?: React.ReactNode;
}

export const MasterLayoutComponent: React.FC<IMasterLayoutComponent> = ({
  children,
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navigation items={NavigationItems} />
      </header>
      <main className="min-h-screen" style={{ paddingTop: "72px" }}>
        {children}
      </main>
      <footer>
        <FooterComponent />
      </footer>
    </div>
  );
};
